# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-17 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190327_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skuspecification',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specs', to='goods.SPUSpecification', verbose_name='规格名称'),
        ),
    ]
